/** All user-facing text, centralized for future RU/EN localization. */
export const UI = {
  appName: 'Anytune',
  screenStrings: 'Strings',
  screenChromatic: 'Chromatic',
  auto: 'Auto',
  startListening: 'Start tuning',
  stopListening: 'Stop',
  starting: 'Starting microphone...',
  playAnyString: 'Play any string to begin',
  playSelectedString: 'Play the selected string',
  playANote: 'Play a note to begin',
  tapAgainToEdit: 'Tap a string to target it, tap again to change its note',
  micDenied: 'Microphone access denied. Allow it in browser settings and retry.',
  micMissing: 'No microphone found on this device.',
  micUnavailable: 'Microphone is unavailable.',
  inTune: 'in tune',
  tighten: 'too low — tighten',
  loosen: 'too high — loosen',
  chromaticFlat: 'flat — tune up',
  chromaticSharp: 'sharp — tune down',
  chromaticCentered: 'centered',
  stringWord: 'String',
  tunings: 'Tunings',
  guitar: 'Guitar',
  bass: 'Bass',
  myTunings: 'My tunings',
  noCustomTunings: 'No saved tunings yet — edit a string, name it, then tap Save above.',
  saveCurrent: 'Save current tuning',
  saveHint: 'Name your tuning, then tap Save to add it under My tunings.',
  namePlaceholder: 'Tuning name',
  save: 'Save',
  close: 'Close',
  delete: 'Delete',
  rename: 'Rename',
  customName: 'Custom',
  installHint: 'Install this app: Share, then "Add to Home Screen"',
  pickNote: 'Choose note',
  octave: 'Octave',
  done: 'Done',
} as const
