/** All user-facing text, centralized for future RU/EN localization. */
export const UI = {
  appName: 'anytune',
  auto: 'Auto',
  startListening: 'Start tuning',
  stopListening: 'Stop',
  starting: 'Starting microphone...',
  playAnyString: 'Play any string to begin',
  playSelectedString: 'Play the selected string',
  tapAgainToEdit: 'Tap a string to target it, tap again to change its note',
  micDenied: 'Microphone access denied. Allow it in browser settings and retry.',
  micMissing: 'No microphone found on this device.',
  micUnavailable: 'Microphone is unavailable.',
  inTune: 'in tune',
  tighten: 'too low — tighten',
  loosen: 'too high — loosen',
  stringWord: 'String',
  tunings: 'Tunings',
  guitar: 'Guitar',
  bass: 'Bass',
  myTunings: 'My tunings',
  saveCurrent: 'Save current tuning',
  namePlaceholder: 'Tuning name',
  save: 'Save',
  close: 'Close',
  delete: 'Delete',
  customName: 'Custom',
  pickNote: 'Choose note',
  octave: 'Octave',
  done: 'Done',
} as const
